import db from './models/index.mjs'
import bcrypt from 'bcrypt'

await db.sequelize.sync()
const passwordHash = await bcrypt.hash('parola123', 10)

const seed = [
  { client: { nume: 'Alexandru Ionescu', email: 'alex.ionescu@gmail.com' }, rezervari: [{ data: '2026-03-15', ora: '19:00', nrPersoane: 2, zona: 'Interior', ocazie: 'Cina Romantica', status: 'confirmata', createdAt: new Date('2026-03-14') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-03-15T19:30:00'), items: [{ preparatId: 2, numeSnapshot: 'Carpaccio di Manzo', pretSnapshot: 72, cantitate: 1 }, { preparatId: 51, numeSnapshot: 'Ribeye Angus 400g', pretSnapshot: 185, cantitate: 1 }, { preparatId: 103, numeSnapshot: 'Spaghetti Carbonara Clasica', pretSnapshot: 72, cantitate: 1 }] }] },
  { client: { nume: 'Maria Popescu', email: 'maria.popescu@gmail.com' }, rezervari: [{ data: '2026-02-14', ora: '20:00', nrPersoane: 4, zona: 'Terasa', ocazie: 'Aniversare', status: 'confirmata', createdAt: new Date('2026-02-13') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-02-14T20:30:00'), items: [{ preparatId: 3, numeSnapshot: 'Burrata cu Rosii Cherry', pretSnapshot: 65, cantitate: 1 }, { preparatId: 77, numeSnapshot: 'Sea Bass in Crusta de Sare', pretSnapshot: 135, cantitate: 1 }, { preparatId: 102, numeSnapshot: 'Risotto ai Funghi Porcini', pretSnapshot: 88, cantitate: 1 }] }] },
  { client: { nume: 'Andrei Dumitrescu', email: 'andrei.dumitrescu@gmail.com' }, rezervari: [], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-01-22T20:00:00'), items: [{ preparatId: 30, numeSnapshot: 'French Onion Soup', pretSnapshot: 58, cantitate: 1 }, { preparatId: 56, numeSnapshot: 'T-Bone Steak 500g', pretSnapshot: 210, cantitate: 1 }] }, { status: 'confirmata', createdAt: new Date('2026-04-10T19:00:00'), items: [{ preparatId: 5, numeSnapshot: 'Arancini cu Mozzarella', pretSnapshot: 52, cantitate: 1 }, { preparatId: 76, numeSnapshot: 'Somon la Gratar', pretSnapshot: 112, cantitate: 1 }] }] },
  { client: { nume: 'Elena Gheorghe', email: 'elena.gheorghe@gmail.com' }, rezervari: [{ data: '2026-04-18', ora: '19:30', nrPersoane: 3, zona: 'Salon Privat', ocazie: 'Business Dinner', status: 'confirmata', createdAt: new Date('2026-04-17') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-04-18T20:00:00'), items: [{ preparatId: 6, numeSnapshot: 'Vitello Tonnato', pretSnapshot: 78, cantitate: 1 }, { preparatId: 54, numeSnapshot: 'Duck Confit', pretSnapshot: 128, cantitate: 1 }, { preparatId: 104, numeSnapshot: 'Linguine alle Vongole', pretSnapshot: 85, cantitate: 1 }] }] },
  { client: { nume: 'Mihai Constantin', email: 'mihai.constantin@gmail.com' }, rezervari: [{ data: '2025-12-31', ora: '20:00', nrPersoane: 6, zona: 'Interior', ocazie: 'Revelion', status: 'confirmata', createdAt: new Date('2025-12-28') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2025-12-31T20:30:00'), items: [{ preparatId: 19, numeSnapshot: 'Foie Gras cu Jeleu de Porto', pretSnapshot: 115, cantitate: 2 }, { preparatId: 57, numeSnapshot: 'Wellington de Vita', pretSnapshot: 245, cantitate: 1 }, { preparatId: 106, numeSnapshot: 'Risotto al Tartufo Nero', pretSnapshot: 115, cantitate: 2 }] }] },
  { client: { nume: 'Ana Maria Popa', email: 'ana.popa@gmail.com' }, rezervari: [], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-03-08T19:00:00'), items: [{ preparatId: 28, numeSnapshot: 'Crema de Dovleac cu Ghimbir', pretSnapshot: 48, cantitate: 1 }, { preparatId: 83, numeSnapshot: 'Homard Grillat', pretSnapshot: 220, cantitate: 1 }] }] },
  { client: { nume: 'Cristian Radu', email: 'cristian.radu@gmail.com' }, rezervari: [{ data: '2026-05-05', ora: '19:00', nrPersoane: 2, zona: 'Terasa', ocazie: null, status: 'confirmata', createdAt: new Date('2026-05-04') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-05-05T19:30:00'), items: [{ preparatId: 10, numeSnapshot: 'Crostini cu Ricotta si Smochine', pretSnapshot: 48, cantitate: 1 }, { preparatId: 52, numeSnapshot: 'Filet Mignon', pretSnapshot: 195, cantitate: 1 }, { preparatId: 101, numeSnapshot: 'Tagliatelle al Ragu Bolognese', pretSnapshot: 78, cantitate: 1 }] }] },
  { client: { nume: 'Ioana Stancu', email: 'ioana.stancu@gmail.com' }, rezervari: [{ data: '2025-11-28', ora: '20:00', nrPersoane: 2, zona: 'Interior', ocazie: 'Aniversare', status: 'confirmata', createdAt: new Date('2025-11-27') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2025-11-28T20:30:00'), items: [{ preparatId: 7, numeSnapshot: 'Tartare de Ton cu Avocado', pretSnapshot: 95, cantitate: 1 }, { preparatId: 81, numeSnapshot: 'Scoici Saint-Jacques', pretSnapshot: 145, cantitate: 1 }] }] },
  { client: { nume: 'Bogdan Marinescu', email: 'bogdan.marinescu@gmail.com' }, rezervari: [], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-02-28T19:00:00'), items: [{ preparatId: 29, numeSnapshot: 'Minestrone Clasica', pretSnapshot: 45, cantitate: 1 }, { preparatId: 55, numeSnapshot: 'Osso Buco Milanese', pretSnapshot: 145, cantitate: 1 }, { preparatId: 105, numeSnapshot: 'Cacio e Pepe', pretSnapshot: 68, cantitate: 1 }] }, { status: 'confirmata', createdAt: new Date('2026-05-12T20:00:00'), items: [{ preparatId: 26, numeSnapshot: 'Bisque de Homar', pretSnapshot: 85, cantitate: 1 }, { preparatId: 53, numeSnapshot: 'Rack of Lamb', pretSnapshot: 175, cantitate: 1 }] }] },
  { client: { nume: 'Raluca Voicu', email: 'raluca.voicu@gmail.com' }, rezervari: [{ data: '2026-01-10', ora: '19:30', nrPersoane: 4, zona: 'Salon Privat', ocazie: null, status: 'confirmata', createdAt: new Date('2026-01-09') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-01-10T20:00:00'), items: [{ preparatId: 5, numeSnapshot: 'Arancini cu Mozzarella', pretSnapshot: 52, cantitate: 2 }, { preparatId: 77, numeSnapshot: 'Sea Bass in Crusta de Sare', pretSnapshot: 135, cantitate: 2 }, { preparatId: 107, numeSnapshot: 'Gnocchi al Gorgonzola', pretSnapshot: 75, cantitate: 2 }] }] },
  { client: { nume: 'Florin Nistor', email: 'florin.nistor@gmail.com' }, rezervari: [], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-04-05T20:30:00'), items: [{ preparatId: 31, numeSnapshot: 'Crema de Ciuperci Porcini', pretSnapshot: 62, cantitate: 1 }, { preparatId: 67, numeSnapshot: 'Chateaubriand pentru 2', pretSnapshot: 380, cantitate: 1 }, { preparatId: 100, numeSnapshot: 'Risotto Nero cu Sepie', pretSnapshot: 105, cantitate: 1 }] }] },
  { client: { nume: 'Diana Preda', email: 'diana.preda@gmail.com' }, rezervari: [{ data: '2026-02-14', ora: '20:00', nrPersoane: 2, zona: 'Interior', ocazie: 'Cina Romantica', status: 'confirmata', createdAt: new Date('2026-02-13') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-02-14T20:30:00'), items: [{ preparatId: 15, numeSnapshot: 'Gravlax de Somon', pretSnapshot: 85, cantitate: 1 }, { preparatId: 79, numeSnapshot: 'Halibut cu Sos de Capere', pretSnapshot: 145, cantitate: 1 }, { preparatId: 117, numeSnapshot: 'Tagliolini al Limone', pretSnapshot: 72, cantitate: 1 }] }] },
  { client: { nume: 'Vlad Stoica', email: 'vlad.stoica@gmail.com' }, rezervari: [], comenzi: [{ status: 'confirmata', createdAt: new Date('2025-12-05T19:00:00'), items: [{ preparatId: 1, numeSnapshot: 'Bruschetta cu Rosii si Busuioc', pretSnapshot: 38, cantitate: 1 }, { preparatId: 69, numeSnapshot: 'Gulash Vienez', pretSnapshot: 95, cantitate: 1 }, { preparatId: 109, numeSnapshot: 'Penne all Arrabbiata', pretSnapshot: 62, cantitate: 1 }] }] },
  { client: { nume: 'Simona Tudor', email: 'simona.tudor@gmail.com' }, rezervari: [{ data: '2026-03-20', ora: '19:00', nrPersoane: 3, zona: 'Terasa', ocazie: null, status: 'confirmata', createdAt: new Date('2026-03-19') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-03-20T19:30:00'), items: [{ preparatId: 8, numeSnapshot: 'Insalata Caprese', pretSnapshot: 58, cantitate: 1 }, { preparatId: 78, numeSnapshot: 'Dorada Mediteraneana', pretSnapshot: 118, cantitate: 1 }, { preparatId: 108, numeSnapshot: 'Tortellini in Brodo', pretSnapshot: 72, cantitate: 1 }] }] },
  { client: { nume: 'Radu Munteanu', email: 'radu.munteanu@gmail.com' }, rezervari: [], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-01-22T20:00:00'), items: [{ preparatId: 33, numeSnapshot: 'Crema de Sparanghel cu Trufe', pretSnapshot: 75, cantitate: 1 }, { preparatId: 61, numeSnapshot: 'Medallions de Vita cu Foie Gras', pretSnapshot: 275, cantitate: 1 }] }, { status: 'confirmata', createdAt: new Date('2026-04-30T20:00:00'), items: [{ preparatId: 9, numeSnapshot: 'Antipasto Misto della Casa', pretSnapshot: 88, cantitate: 1 }, { preparatId: 88, numeSnapshot: 'Langoustine Grillate', pretSnapshot: 175, cantitate: 1 }, { preparatId: 112, numeSnapshot: 'Ravioli di Ricotta e Spinaci', pretSnapshot: 82, cantitate: 1 }] }] },
  { client: { nume: 'Alina Dobre', email: 'alina.dobre@gmail.com' }, rezervari: [{ data: '2025-12-20', ora: '20:30', nrPersoane: 4, zona: 'Salon Privat', ocazie: 'Petrecere', status: 'confirmata', createdAt: new Date('2025-12-18') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2025-12-20T21:00:00'), items: [{ preparatId: 4, numeSnapshot: 'Prosciutto e Melone', pretSnapshot: 68, cantitate: 2 }, { preparatId: 72, numeSnapshot: 'Pui Tikka Masala', pretSnapshot: 82, cantitate: 2 }, { preparatId: 110, numeSnapshot: 'Pasta al Pesto Genovese', pretSnapshot: 72, cantitate: 2 }] }] },
  { client: { nume: 'Claudiu Petrescu', email: 'claudiu.petrescu@gmail.com' }, rezervari: [], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-03-08T19:00:00'), items: [{ preparatId: 35, numeSnapshot: 'Zuppa Toscana', pretSnapshot: 55, cantitate: 1 }, { preparatId: 63, numeSnapshot: 'Entrecote cu Bearnaise', pretSnapshot: 158, cantitate: 1 }] }] },
  { client: { nume: 'Gabriela Lazar', email: 'gabriela.lazar@gmail.com' }, rezervari: [{ data: '2026-04-30', ora: '19:30', nrPersoane: 2, zona: 'Interior', ocazie: 'Aniversare', status: 'confirmata', createdAt: new Date('2026-04-29') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-04-30T20:00:00'), items: [{ preparatId: 23, numeSnapshot: 'Baked Camembert', pretSnapshot: 68, cantitate: 1 }, { preparatId: 76, numeSnapshot: 'Somon la Gratar', pretSnapshot: 112, cantitate: 1 }, { preparatId: 113, numeSnapshot: 'Fettuccine Alfredo', pretSnapshot: 68, cantitate: 1 }] }] },
  { client: { nume: 'Ionut Barbu', email: 'ionut.barbu@gmail.com' }, rezervari: [], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-02-14T20:00:00'), items: [{ preparatId: 13, numeSnapshot: 'Bruschetta cu Ciuperci si Trufe', pretSnapshot: 62, cantitate: 1 }, { preparatId: 64, numeSnapshot: 'Coasta de Vita Gatita 12h', pretSnapshot: 165, cantitate: 1 }, { preparatId: 111, numeSnapshot: 'Bucatini all Amatriciana', pretSnapshot: 75, cantitate: 1 }] }] },
  { client: { nume: 'Andreea Serban', email: 'andreea.serban@gmail.com' }, rezervari: [{ data: '2026-05-12', ora: '20:00', nrPersoane: 6, zona: 'Interior', ocazie: 'Aniversare', status: 'confirmata', createdAt: new Date('2026-05-10') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-05-12T20:30:00'), items: [{ preparatId: 12, numeSnapshot: 'Calamari Fritti', pretSnapshot: 58, cantitate: 2 }, { preparatId: 80, numeSnapshot: 'Bouillabaisse Provencala', pretSnapshot: 155, cantitate: 2 }, { preparatId: 119, numeSnapshot: 'Risotto cu Creveti si Lemon Zest', pretSnapshot: 95, cantitate: 2 }] }] },
  { client: { nume: 'Marius Neagu', email: 'marius.neagu@gmail.com' }, rezervari: [], comenzi: [{ status: 'confirmata', createdAt: new Date('2025-11-15T20:00:00'), items: [{ preparatId: 11, numeSnapshot: 'Tartare de Vita cu Trufe', pretSnapshot: 120, cantitate: 1 }, { preparatId: 57, numeSnapshot: 'Wellington de Vita', pretSnapshot: 245, cantitate: 1 }] }, { status: 'confirmata', createdAt: new Date('2026-03-20T20:00:00'), items: [{ preparatId: 42, numeSnapshot: 'Supa Crema de Trufe', pretSnapshot: 88, cantitate: 1 }, { preparatId: 68, numeSnapshot: 'Miel in Crusta de Ierburi', pretSnapshot: 168, cantitate: 1 }] }] },
  { client: { nume: 'Catalina Oprea', email: 'catalina.oprea@gmail.com' }, rezervari: [{ data: '2026-01-22', ora: '19:00', nrPersoane: 2, zona: 'Terasa', ocazie: 'Cina Romantica', status: 'confirmata', createdAt: new Date('2026-01-21') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-01-22T19:30:00'), items: [{ preparatId: 24, numeSnapshot: 'Oysters Rockefeller', pretSnapshot: 110, cantitate: 1 }, { preparatId: 82, numeSnapshot: 'Ton Tataki', pretSnapshot: 135, cantitate: 1 }, { preparatId: 114, numeSnapshot: 'Orecchiette con Cime di Rapa', pretSnapshot: 75, cantitate: 1 }] }] },
  { client: { nume: 'Stefan Coman', email: 'stefan.coman@gmail.com' }, rezervari: [], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-04-18T19:00:00'), items: [{ preparatId: 16, numeSnapshot: 'Polenta Prajita cu Gorgonzola', pretSnapshot: 52, cantitate: 1 }, { preparatId: 71, numeSnapshot: 'Pui Massaman Curry', pretSnapshot: 85, cantitate: 1 }, { preparatId: 115, numeSnapshot: 'Rigatoni alla Norma', pretSnapshot: 68, cantitate: 1 }] }] },
  { client: { nume: 'Roxana Filip', email: 'roxana.filip@gmail.com' }, rezervari: [{ data: '2026-02-28', ora: '19:30', nrPersoane: 3, zona: 'Interior', ocazie: null, status: 'confirmata', createdAt: new Date('2026-02-27') }], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-02-28T20:00:00'), items: [{ preparatId: 17, numeSnapshot: 'Tapenade cu Masline Negre', pretSnapshot: 42, cantitate: 1 }, { preparatId: 78, numeSnapshot: 'Dorada Mediteraneana', pretSnapshot: 118, cantitate: 1 }, { preparatId: 103, numeSnapshot: 'Spaghetti Carbonara Clasica', pretSnapshot: 72, cantitate: 1 }] }] },
  { client: { nume: 'George Apostol', email: 'george.apostol@gmail.com' }, rezervari: [], comenzi: [{ status: 'confirmata', createdAt: new Date('2026-05-05T20:00:00'), items: [{ preparatId: 26, numeSnapshot: 'Bisque de Homar', pretSnapshot: 85, cantitate: 1 }, { preparatId: 51, numeSnapshot: 'Ribeye Angus 400g', pretSnapshot: 185, cantitate: 1 }, { preparatId: 102, numeSnapshot: 'Risotto ai Funghi Porcini', pretSnapshot: 88, cantitate: 1 }] }] }
]

let created = 0
for (const entry of seed) {
  const existent = await db.User.findOne({ where: { email: entry.client.email } })
  if (existent) { console.log(`Skip: ${entry.client.email}`); continue }
  const user = await db.User.create({ ...entry.client, passwordHash, tip: 'client' })
  const rezervariCreate = []
  for (const rez of (entry.rezervari || [])) {
    const r = await db.Rezervare.create({ ...rez, userId: user.id })
    rezervariCreate.push(r)
  }
  for (let i = 0; i < entry.comenzi.length; i++) {
    const cmd = entry.comenzi[i]
    const total = cmd.items.reduce((sum, j) => sum + j.pretSnapshot * j.cantitate, 0)
    const rezervareId = rezervariCreate[i]?.id || null
    const comanda = await db.Comanda.create({ userId: user.id, status: cmd.status, total, rezervareId, createdAt: cmd.createdAt, updatedAt: cmd.createdAt })
    for (const item of cmd.items) {
      await db.ComandaItem.create({ ...item, comandaId: comanda.id })
    }
  }
  created++
  console.log(`Creat: ${entry.client.nume}`)
}
console.log(`\nGata! ${created} clienti noi creati.`)
process.exit(0)
